FROM ghcr.io/tauffer-consulting/domino-base-piece:latest

# Install specific requirements
RUN apt update
RUN apt install -y openjdk-17-jdk

# Need to copy pieces source code
COPY config.toml domino/pieces_repository/
COPY pieces domino/pieces_repository/pieces
COPY .domino domino/pieces_repository/.domino

# Install specific python dependencies
RUN pip install h2o
RUN pip install pandas
RUN pip install matplotlib